version: "3"

services:
  model-service:
    image: ghcr.io/remla2024-team9/model-service:latest
    ports:
      - "5000:5000"
    networks:
      - my-net

  app-service:
    image: ghcr.io/remla2024-team9/app-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - model-service
    networks:
      - my-net
    environment:
      - MODEL_SERVICE_URL=http://model-service:5000

  app-frontend:
    image: ghcr.io/remla2024-team9/app-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - app-service
    networks:
      - my-net
    environment:
      - REACT_APP_BACKEND_URL=http://app-service:8080

networks:
  my-net:
    driver: bridge
