---
- hosts: workers
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Add Vagrant user to Docker group
      user:
        name: vagrant
        groups: docker
        append: true

    - name: Install Minikube from latest release
      apt:
        deb: "https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb"
        state: present
