---
- hosts: controller
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Add Vagrant user to Docker group
      user:
        name: vagrant
        groups: docker
        append: true

    - name: Install Minikube from latest release
      apt:
        deb: "https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb"
        state: present
    
    - name: Get latest kubectl version
      command: curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
      register: kubectl_version

    - name: Download kubectl
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
    
    - name: Refresh user groups
      command: newgrp docker
      become_user: vagrant
    
    - name: Start Minikube with Docker driver
      command: minikube start --driver=docker
      become_user: vagrant

    - name: Enable Minikube ingress addon
      command: minikube addons enable ingress
      become_user: vagrant

    - name: Verify Minikube cluster information
      command: kubectl cluster-info
      register: cluster_info_output
      become_user: vagrant

    - name: Display cluster information
      debug:
        var: cluster_info_output.stdout
