---
- name: Join k3s Kubernetes Cluster
  hosts: workers
  become: yes
  tasks:
    - name: Read k3s token from shared folder
      command: cat /vagrant_data/k3s_token.txt
      register: k3s_token

    - name: Read master IP from shared folder
      command: cat /vagrant_data/master_ip.txt
      register: master_ip

    - name: Debug k3s token and master IP
      debug:
        msg: "K3S_TOKEN={{ k3s_token.stdout }}, MASTER_IP={{ master_ip.stdout }}"

    - name: Join k3s cluster
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip.stdout }}:6444 K3S_TOKEN={{ k3s_token.stdout }} sh -
      args:
        executable: /bin/bash
      register: join_result
    
    - name: Print join result
      debug:
        var: join_result

