---
- name: Setup k3s Kubernetes Cluster
  hosts: controller
  become: yes
  tasks:
    - name: Install k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        executable: /bin/bash

    - name: Retrieve k3s join token
      shell: "cat /var/lib/rancher/k3s/server/node-token"
      register: k3s_token

    - name: Save k3s join token to shared folder
      copy:
        content: "{{ k3s_token.stdout }}"
        dest: /vagrant_data/k3s_token.txt

    - name: Get master node IP
      shell: "hostname -I | awk '{print $2}'"
      register: master_ip

    - name: Save master IP to shared folder
      copy:
        content: "{{ master_ip.stdout }}"
        dest: /vagrant_data/master_ip.txt
