---
- name: Set up K3s server
  hosts: controller
  become: yes
  vars:
    master_node_ip: "192.168.57.10"

  tasks:
    - name: Install K3s server with TLS and external IP settings
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san {{ master_node_ip }} --node-external-ip {{ master_node_ip }}" K3S_NODE_NAME="$HOSTNAME" K3S_KUBECONFIG_MODE="644" sh -
      args:
        executable: /bin/bash

    - name: Wait for K3s server to be ready
      shell: |
        until k3s kubectl get node; do
          sleep 2
        done
      retries: 10
      delay: 15
      register: k3s_server_ready
      until: k3s_server_ready is succeeded

    - name: Fetch K3s token
      fetch:
        src: /var/lib/rancher/k3s/server/node-token
        dest: /vagrant/shared_folder/node-token
        flat: yes

    - name: Create .kube directory
      file:
        path: /home/vagrant/.kube
        state: directory
        mode: '0755'

    - name: Set up kubectl for local use
      shell: |
        k3s kubectl config view --raw > /home/vagrant/.kube/config
      args:
        executable: /bin/bash

    - name: Label the node for ingress-nginx
      shell: |
        kubectl label nodes $(kubectl get nodes -o jsonpath='{.items[0].metadata.name}') ingress-ready=true kubernetes.io/os=linux
      args:
        executable: /bin/bash

    - name: Create namespace for ingress-nginx
      shell: kubectl create namespace ingress-nginx || true
      args:
        executable: /bin/bash

    - name: Install NGINX Ingress Controller
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
      args:
        executable: /bin/bash

    - name: Wait for NGINX Ingress Controller to be ready
      shell: |
        while [[ $(kubectl get pods -n ingress-nginx -l app.kubernetes.io/component=controller -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do
          echo "waiting for ingress controller to be ready" && sleep 10;
        done
      args:
        executable: /bin/bash

    - name: Deploy application to Kubernetes
      shell: kubectl apply -f /vagrant/kubernetes/
      args:
        executable: /bin/bash

    - name: Deploy Ingress
      shell: kubectl apply -f /vagrant/kubernetes/ingress.yml
      args:
        executable: /bin/bash
