---
- hosts: controller
  become: yes
  tasks:
    - name: Update apt repository and cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present
