---
- name: Set up K3s agent
  hosts: workers
  become: yes
  tasks:
    - name: Debug network connectivity
      command: ping -c 4 192.168.57.10
      register: ping_result

    - name: Display ping result
      debug:
        var: ping_result
        
    - name: Verify connectivity to the controller
      wait_for:
        host: 192.168.57.10
        port: 6443
        delay: 5
        timeout: 15
        state: started

    - name: Install K3s agent
      shell: >
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['controller']['ansible_default_ipv4']['address'] }}:6443 K3S_TOKEN=$(cat /vagrant/shared_folder/node-token) sh -
