apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env-vars
data:
  appConfig.js: |
    window.appConfig = {
        REACT_APP_BACKEND_URL: "http://app-service.default.svc.cluster.local:8080"
    };

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
data:
  default.conf: |
    server {
      listen 3000;

      server_name 0.0.0.0;

      location / {
          root /usr/share/nginx/html;
          index index.html;
          try_files $uri $uri/ /index.html;
      }

      location /submit_input {
          proxy_pass http://app-service.default.svc.cluster.local:8080;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
      }
    }
