apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
  labels:
    app: model-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
        version: v1
    spec:
      containers:
        - name: model-service
          image: erenaydoslue/model-service:latest #ghcr.io/remla2024-team9/model-service:v0.1.11
          ports:
            - containerPort: 5000
            - containerPort: 8000 # port for metrics
