apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  labels:
    app: app-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
        version: v1
    spec:
      containers:
        - name: app-service
          image: ghcr.io/remla2024-team9/app-service:latest
          ports:
            - containerPort: 8080
            - containerPort: 8000 # port for metrics
          env:
            - name: MODEL_SERVICE_URL
              value: "http://model-service.default.svc.cluster.local:5000"
