apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  labels:
    app: app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
        - name: app-frontend
          image: erenaydoslue/remla:latest #samuelribaric/appfrontend:latest  #ghcr.io/remla2024-team9/app-frontend:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            # - name: app-config-volume
            #   mountPath: /usr/share/nginx/html/appConfig.js
            #   subPath: appConfig.js

            - name: app-nginx-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

      volumes:
        # - name: app-config-volume
        #   configMap:
        #     name: frontend-env-vars
        - name: app-nginx-volume
          configMap:
            name: frontend-nginx-conf
