apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  labels:
    app: app-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
        version: v1
    spec:
      containers:
        - name: app-frontend
          image: ghcr.io/remla2024-team9/app-frontend:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: app-nginx-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: app-nginx-volume
          configMap:
            name: frontend-nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend
spec:
  selector:
    app: app-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
