apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: app-service
          image: erenaydoslue/app-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: MODEL_SERVICE_URL
              value: "http://model-service.default.svc.cluster.local:5000"
