apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
  labels:
    app: model-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
      version: v1
  template:
    metadata:
      labels:
        app: model-service
        version: v1
    spec:
      containers:
        - name: model-service
          image: ghcr.io/remla2024-team9/model-service:v0.1.15
          ports:
            - containerPort: 5000
            - containerPort: 8001 # port for metrics
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
