apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-frontend
                port:
                  number: 3000

          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443

          # - path: /api
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: app-service
          #       port:
          #         number: 8080
          # - path: /model
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: model-service
          #       port:
          #         number: 5000
