apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: default
spec:
  selector:
    app: model-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
