apiVersion: v1
kind: Service
metadata:
  name: app-frontend
  namespace: default
spec:
  selector:
    app: app-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
